name: Build

on:
  workflow_dispatch:
    inputs:
      build:
        description: 'Build'
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Node.js Setup
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
      - name: TypeScript Build
        run: |
          npm install
          tsc
      - name: Zop Archive
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: 'zip'
          filename: 'SimpleTimer-Extension.zip'
          exclusions: '*.git* /*node_modules/* /*src/* *.idea* package.json package-lock.json tsconfig.json'
      - name: Upload Release
        uses: ncipollo/release-action@v1.12.0
        with:
          artifacts: "SimpleTimer-Extension.zip"
          tag: "Build-${{ github.run_id }}${{ github.run_attempt }}-${{ github.ref_name }}"
          token: ${{ secrets.GITHUB_TOKEN }}
